export type Category =
  | "Cement & Concrete"
  | "Steel & Rebar"
  | "Timber & Boards"
  | "Bricks & Blocks"
  | "Aggregates"
  | "Tools & Safety"
  | "Plumbing"
  | "Electrical"
  | "Flooring & Tiles"
  | "Paint & Finishes"
  | "Interiors & Fittings";

export const CATEGORIES: Category[] = [
  "Cement & Concrete",
  "Steel & Rebar",
  "Timber & Boards",
  "Bricks & Blocks",
  "Aggregates",
  "Plumbing",
  "Electrical",
  "Flooring & Tiles",
  "Paint & Finishes",
  "Interiors & Fittings",
  "Tools & Safety",
];


export type Supplier = {
  id: string;
  name: string;
  city: string;
  since: number;
  rating: number;
  blurb: string;
  fulfilment: string;
};

export const SUPPLIERS: Supplier[] = [
  {
    id: "granite-yard",
    name: "Granite Yard Supply",
    city: "Pune, MH",
    since: 1998,
    rating: 4.8,
    blurb:
      "Bulk aggregates and ready-mix specialists serving contractors across western India. Weighbridge-verified loads on every dispatch.",
    fulfilment: "Own fleet · 24–48h regional delivery",
  },
  {
    id: "ironline",
    name: "Ironline Steel Co.",
    city: "Raipur, CG",
    since: 2005,
    rating: 4.6,
    blurb:
      "Mill-direct TMT bars, structural sections and binding wire. Every batch shipped with test certificates.",
    fulfilment: "Mill dispatch · 3–5 day lead time",
  },
  {
    id: "northwood",
    name: "Northwood Timber",
    city: "Kochi, KL",
    since: 2011,
    rating: 4.7,
    blurb:
      "Kiln-dried structural timber, marine ply and shuttering boards cut to site dimensions.",
    fulfilment: "Cut-to-size · 2–4 day delivery",
  },
  {
    id: "sitekit",
    name: "SiteKit Traders",
    city: "Gurugram, HR",
    since: 2017,
    rating: 4.5,
    blurb:
      "Power tools, PPE and site consumables. Contractor accounts get consolidated monthly invoicing.",
    fulfilment: "Next-day metro delivery",
  },
  {
    id: "aquaflow",
    name: "Aquaflow Plumbing Depot",
    city: "Ahmedabad, GJ",
    since: 2009,
    rating: 4.6,
    blurb:
      "CPVC, UPVC and sanitaryware distributor stocking complete bathroom and water-supply packages for residential builds.",
    fulfilment: "Warehouse pick-up · 2-day city delivery",
  },
  {
    id: "voltcore",
    name: "Voltcore Electricals",
    city: "Bengaluru, KA",
    since: 2013,
    rating: 4.7,
    blurb:
      "ISI-marked wires, switchgear and modular accessories. House-wiring bill of materials prepared from your floor plan.",
    fulfilment: "Next-day dispatch · pan-India courier",
  },
  {
    id: "tilehaus",
    name: "TileHaus Surfaces",
    city: "Morbi, GJ",
    since: 2007,
    rating: 4.5,
    blurb:
      "Factory-direct vitrified tiles, natural stone and laying chemicals shipped by the container load.",
    fulfilment: "Factory dispatch · 4–6 day lead time",
  },
  {
    id: "chromacoat",
    name: "ChromaCoat Paints",
    city: "Nashik, MH",
    since: 2015,
    rating: 4.6,
    blurb:
      "Putty, primers, emulsions and waterproof coatings with on-site shade matching for large residential jobs.",
    fulfilment: "Tinted to order · 2–3 day delivery",
  },
  {
    id: "interia",
    name: "Interia Fit-Out Works",
    city: "Hyderabad, TS",
    since: 2016,
    rating: 4.4,
    blurb:
      "Doors, windows, false-ceiling systems and joinery boards for the finishing stage of residential projects.",
    fulfilment: "Made-to-size · 5–7 day lead time",
  },
  {
    id: "nestcraft",
    name: "Nestcraft Modular",
    city: "Bengaluru, KA",
    since: 2018,
    rating: 4.7,
    blurb:
      "Modular kitchen, wardrobe and storage systems with European hardware, made to site dimensions.",
    fulfilment: "Factory build · 10–14 day lead time",
  },
  {
    id: "lumina-decor",
    name: "Lumina Lighting & Decor",
    city: "Mumbai, MH",
    since: 2012,
    rating: 4.5,
    blurb:
      "Decorative lighting, mirrors, blinds and soft furnishing hardware for residential interiors.",
    fulfilment: "Courier dispatch · 3–5 day delivery",
  },
];


export type Product = {
  id: string;
  name: string;
  category: Category;
  supplierId: string;
  price: number;
  unit: string;
  moq: number;
  stock: number;
  grade: string;
  description: string;
  specs: { label: string; value: string }[];
};

export const PRODUCTS: Product[] = [
  {
    id: "opc-53-cement",
    name: "OPC 53 Grade Cement",
    category: "Cement & Concrete",
    supplierId: "granite-yard",
    price: 395,
    unit: "50 kg bag",
    moq: 20,
    stock: 4200,
    grade: "IS 269:2015",
    description:
      "High early-strength ordinary portland cement for structural concrete, precast and high-load slabs.",
    specs: [
      { label: "Compressive strength", value: "53 MPa @ 28 days" },
      { label: "Setting time", value: "Initial 30 min / Final 600 min" },
      { label: "Packing", value: "50 kg laminated bag" },
      { label: "Shelf life", value: "90 days from packing" },
    ],
  },
  {
    id: "ppc-cement",
    name: "PPC Blended Cement",
    category: "Cement & Concrete",
    supplierId: "granite-yard",
    price: 352,
    unit: "50 kg bag",
    moq: 20,
    stock: 3100,
    grade: "IS 1489",
    description:
      "Fly-ash blended cement with lower heat of hydration — ideal for masonry, plaster and mass pours.",
    specs: [
      { label: "Compressive strength", value: "33 MPa @ 28 days" },
      { label: "Fly ash content", value: "25–30%" },
      { label: "Packing", value: "50 kg laminated bag" },
      { label: "Best for", value: "Plaster, masonry, foundations" },
    ],
  },
  {
    id: "rmc-m25",
    name: "Ready-Mix Concrete M25",
    category: "Cement & Concrete",
    supplierId: "granite-yard",
    price: 4850,
    unit: "cu.m",
    moq: 3,
    stock: 180,
    grade: "M25",
    description:
      "Batching-plant concrete delivered in transit mixers with slump verified at site before discharge.",
    specs: [
      { label: "Grade", value: "M25 (25 N/mm²)" },
      { label: "Slump", value: "100–150 mm" },
      { label: "Aggregate", value: "20 mm graded" },
      { label: "Pump", value: "Boom pump available on request" },
    ],
  },
  {
    id: "tmt-12mm",
    name: "TMT Rebar Fe500D — 12 mm",
    category: "Steel & Rebar",
    supplierId: "ironline",
    price: 62,
    unit: "kg",
    moq: 500,
    stock: 96000,
    grade: "Fe500D",
    description:
      "Thermo-mechanically treated ribbed bars with high ductility for seismic-zone reinforcement.",
    specs: [
      { label: "Yield strength", value: "500 N/mm² min" },
      { label: "Elongation", value: "16% min" },
      { label: "Standard length", value: "12 m" },
      { label: "Certification", value: "Mill test certificate included" },
    ],
  },
  {
    id: "tmt-16mm",
    name: "TMT Rebar Fe550D — 16 mm",
    category: "Steel & Rebar",
    supplierId: "ironline",
    price: 64.5,
    unit: "kg",
    moq: 500,
    stock: 71000,
    grade: "Fe550D",
    description:
      "Heavier-gauge reinforcement for columns, beams and raft foundations in high-rise work.",
    specs: [
      { label: "Yield strength", value: "550 N/mm² min" },
      { label: "Bend test", value: "Passes 3d mandrel" },
      { label: "Standard length", value: "12 m" },
      { label: "Cut & bend", value: "Available at +₹3.50/kg" },
    ],
  },
  {
    id: "ms-angle",
    name: "MS Angle 50×50×5 mm",
    category: "Steel & Rebar",
    supplierId: "ironline",
    price: 58,
    unit: "kg",
    moq: 250,
    stock: 24000,
    grade: "IS 2062 E250",
    description:
      "Hot-rolled mild steel angle for trusses, gates, scaffolding brackets and structural framing.",
    specs: [
      { label: "Section", value: "50 × 50 × 5 mm" },
      { label: "Unit weight", value: "3.8 kg/m" },
      { label: "Length", value: "6 m standard" },
      { label: "Finish", value: "Black / mill finish" },
    ],
  },
  {
    id: "shuttering-ply",
    name: "Film-Faced Shuttering Ply 12 mm",
    category: "Timber & Boards",
    supplierId: "northwood",
    price: 1780,
    unit: "8×4 sheet",
    moq: 10,
    stock: 640,
    grade: "BWP",
    description:
      "Phenolic film-faced plywood engineered for 20+ concrete pours with a clean off-form finish.",
    specs: [
      { label: "Size", value: "2440 × 1220 mm" },
      { label: "Thickness", value: "12 mm" },
      { label: "Repetitions", value: "20–25 pours" },
      { label: "Bond", value: "Boiling water proof" },
    ],
  },
  {
    id: "pine-batten",
    name: "Kiln-Dried Pine Batten 2×3 in",
    category: "Timber & Boards",
    supplierId: "northwood",
    price: 92,
    unit: "running ft",
    moq: 100,
    stock: 12500,
    grade: "C16",
    description:
      "Structural-grade softwood batten for formwork bracing, partitions and temporary works.",
    specs: [
      { label: "Section", value: "50 × 75 mm" },
      { label: "Moisture", value: "12–16%" },
      { label: "Treatment", value: "Borate treated" },
      { label: "Cut to size", value: "Free on orders above 500 ft" },
    ],
  },
  {
    id: "marine-ply",
    name: "Marine Plywood 19 mm",
    category: "Timber & Boards",
    supplierId: "northwood",
    price: 2650,
    unit: "8×4 sheet",
    moq: 6,
    stock: 310,
    grade: "IS 710",
    description:
      "Hardwood-core marine ply for wet areas, joinery and permanent interior structures.",
    specs: [
      { label: "Size", value: "2440 × 1220 mm" },
      { label: "Core", value: "Full hardwood" },
      { label: "Warranty", value: "15 years against borer" },
      { label: "Bond", value: "IS 710 BWP" },
    ],
  },
  {
    id: "aac-block",
    name: "AAC Block 600×200×150 mm",
    category: "Bricks & Blocks",
    supplierId: "granite-yard",
    price: 58,
    unit: "block",
    moq: 200,
    stock: 18400,
    grade: "Grade 1",
    description:
      "Autoclaved aerated concrete blocks — a third the weight of clay brick with better thermal performance.",
    specs: [
      { label: "Dry density", value: "550–650 kg/m³" },
      { label: "Compressive strength", value: "4 N/mm²" },
      { label: "Fire rating", value: "4 hours" },
      { label: "Coverage", value: "55 blocks/m³" },
    ],
  },
  {
    id: "clay-brick",
    name: "First-Class Clay Brick",
    category: "Bricks & Blocks",
    supplierId: "granite-yard",
    price: 9.5,
    unit: "brick",
    moq: 1000,
    stock: 220000,
    grade: "Class A",
    description:
      "Table-moulded kiln-fired bricks with sharp edges and consistent burn — low water absorption.",
    specs: [
      { label: "Size", value: "230 × 110 × 75 mm" },
      { label: "Compressive strength", value: "10.5 N/mm²" },
      { label: "Water absorption", value: "< 15%" },
      { label: "Load", value: "5000 bricks per truck" },
    ],
  },
  {
    id: "river-sand",
    name: "Washed River Sand (Fine)",
    category: "Aggregates",
    supplierId: "granite-yard",
    price: 2450,
    unit: "tonne",
    moq: 5,
    stock: 960,
    grade: "Zone II",
    description:
      "Silt-washed fine aggregate for plaster and masonry mortar. Weighbridge slip with every load.",
    specs: [
      { label: "Grading zone", value: "Zone II" },
      { label: "Silt content", value: "< 3%" },
      { label: "Fineness modulus", value: "2.6–2.9" },
      { label: "Load size", value: "5 / 10 / 20 tonne tippers" },
    ],
  },
  {
    id: "crushed-stone",
    name: "Crushed Stone Aggregate 20 mm",
    category: "Aggregates",
    supplierId: "granite-yard",
    price: 1180,
    unit: "tonne",
    moq: 10,
    stock: 3400,
    grade: "IS 383",
    description:
      "Angular granite aggregate for structural concrete, PCC beds and road base layers.",
    specs: [
      { label: "Nominal size", value: "20 mm" },
      { label: "Flakiness index", value: "< 25%" },
      { label: "Impact value", value: "< 24%" },
      { label: "Source", value: "Granite quarry, crushed" },
    ],
  },
  {
    id: "rotary-hammer",
    name: "SDS-Plus Rotary Hammer 900 W",
    category: "Tools & Safety",
    supplierId: "sitekit",
    price: 8990,
    unit: "unit",
    moq: 1,
    stock: 120,
    grade: "Pro duty",
    description:
      "Three-mode hammer drill for concrete anchoring and chiselling, with vibration control grip.",
    specs: [
      { label: "Power", value: "900 W" },
      { label: "Impact energy", value: "3.2 J" },
      { label: "Chuck", value: "SDS-Plus" },
      { label: "Warranty", value: "1 year on-site" },
    ],
  },
  {
    id: "safety-helmet",
    name: "Ratchet Safety Helmet (Pack of 10)",
    category: "Tools & Safety",
    supplierId: "sitekit",
    price: 2350,
    unit: "pack of 10",
    moq: 2,
    stock: 480,
    grade: "IS 2925",
    description:
      "HDPE shell helmets with ratchet suspension and chin strap. Site-branding available on bulk orders.",
    specs: [
      { label: "Shell", value: "HDPE, UV stabilised" },
      { label: "Suspension", value: "6-point ratchet" },
      { label: "Standard", value: "IS 2925 certified" },
      { label: "Colours", value: "White, yellow, blue, red" },
    ],
  },
  {
    id: "scaffold-frame",
    name: "Steel Scaffolding Frame Set",
    category: "Tools & Safety",
    supplierId: "sitekit",
    price: 4200,
    unit: "set",
    moq: 4,
    stock: 260,
    grade: "Heavy duty",
    description:
      "Galvanised H-frame scaffolding with cross braces and base jacks for facade and slab work.",
    specs: [
      { label: "Frame height", value: "1.7 m" },
      { label: "Load capacity", value: "450 kg/bay" },
      { label: "Finish", value: "Hot-dip galvanised" },
      { label: "Includes", value: "2 frames, 2 braces, 4 jacks" },
    ],
  },
  {
    id: "cpvc-pipe",
    name: "CPVC Pipe 25 mm SDR 11",
    category: "Plumbing",
    supplierId: "aquaflow",
    price: 385,
    unit: "3 m length",
    moq: 20,
    stock: 1800,
    grade: "ASTM D2846",
    description:
      "Hot and cold water supply pipe for concealed residential plumbing, rated for 82°C continuous use.",
    specs: [
      { label: "Outer diameter", value: "25 mm (1 in)" },
      { label: "Pressure rating", value: "SDR 11 / 11 bar" },
      { label: "Length", value: "3 m" },
      { label: "Joint", value: "Solvent weld" },
    ],
  },
  {
    id: "upvc-swr",
    name: "UPVC SWR Drain Pipe 110 mm",
    category: "Plumbing",
    supplierId: "aquaflow",
    price: 720,
    unit: "3 m length",
    moq: 10,
    stock: 940,
    grade: "IS 13592 Type B",
    description:
      "Soil, waste and rainwater pipe for stacks and horizontal drain runs with ring-fit joints.",
    specs: [
      { label: "Diameter", value: "110 mm" },
      { label: "Type", value: "Type B (soil & waste)" },
      { label: "Joint", value: "Elastomeric ring fit" },
      { label: "Length", value: "3 m" },
    ],
  },
  {
    id: "brass-valve",
    name: "Brass Ball Valve 25 mm",
    category: "Plumbing",
    supplierId: "aquaflow",
    price: 640,
    unit: "unit",
    moq: 10,
    stock: 620,
    grade: "CW617N brass",
    description:
      "Full-bore forged brass isolation valve for supply lines, terrace tanks and manifold headers.",
    specs: [
      { label: "Size", value: "25 mm / 1 in BSP" },
      { label: "Body", value: "Forged brass, chrome plated" },
      { label: "Pressure", value: "PN 25" },
      { label: "Handle", value: "Lever, lockable" },
    ],
  },
  {
    id: "solvent-cement",
    name: "CPVC Solvent Cement 500 ml",
    category: "Plumbing",
    supplierId: "aquaflow",
    price: 480,
    unit: "500 ml tin",
    moq: 6,
    stock: 410,
    grade: "ASTM F493",
    description:
      "One-step heavy-bodied solvent cement for permanent CPVC joints, no primer required.",
    specs: [
      { label: "Coverage", value: "~120 joints of 25 mm" },
      { label: "Set time", value: "15 min handling" },
      { label: "Shelf life", value: "24 months sealed" },
      { label: "Applicator", value: "Brush in cap" },
    ],
  },
  {
    id: "water-tank",
    name: "Triple-Layer Water Tank 1000 L",
    category: "Plumbing",
    supplierId: "aquaflow",
    price: 8450,
    unit: "unit",
    moq: 1,
    stock: 140,
    grade: "IS 12701",
    description:
      "UV-stabilised roto-moulded overhead tank with food-grade inner layer and insulating middle layer.",
    specs: [
      { label: "Capacity", value: "1000 litres" },
      { label: "Layers", value: "3 (UV / foam / food grade)" },
      { label: "Warranty", value: "7 years" },
      { label: "Inlet/outlet", value: "25 mm threaded" },
    ],
  },
  {
    id: "wc-suite",
    name: "Wall-Hung WC with Concealed Cistern",
    category: "Plumbing",
    supplierId: "aquaflow",
    price: 18900,
    unit: "set",
    moq: 1,
    stock: 85,
    grade: "Vitreous china",
    description:
      "Rimless wall-hung pan, concealed cistern frame and dual-flush plate — complete bathroom fit-out set.",
    specs: [
      { label: "Flush", value: "Dual 3/6 litre" },
      { label: "Includes", value: "Pan, frame, cistern, plate, seat" },
      { label: "Load rating", value: "400 kg frame" },
      { label: "Finish", value: "Glossy white" },
    ],
  },
  {
    id: "washbasin",
    name: "Counter-Top Ceramic Washbasin",
    category: "Plumbing",
    supplierId: "aquaflow",
    price: 4650,
    unit: "unit",
    moq: 2,
    stock: 210,
    grade: "Vitreous china",
    description:
      "Above-counter basin with anti-stain glaze for bathroom vanities and utility counters.",
    specs: [
      { label: "Size", value: "560 × 400 × 145 mm" },
      { label: "Tap hole", value: "Single, centre" },
      { label: "Waste", value: "32 mm, not included" },
      { label: "Finish", value: "White glaze" },
    ],
  },
  {
    id: "mixer-tap",
    name: "Single-Lever Basin Mixer",
    category: "Plumbing",
    supplierId: "aquaflow",
    price: 3250,
    unit: "unit",
    moq: 4,
    stock: 300,
    grade: "Brass, chrome",
    description:
      "Ceramic-cartridge mixer tap with aerator for hot and cold basin supply.",
    specs: [
      { label: "Cartridge", value: "35 mm ceramic disc" },
      { label: "Body", value: "Brass, chrome plated" },
      { label: "Flow", value: "6 l/min aerated" },
      { label: "Warranty", value: "5 years" },
    ],
  },
  {
    id: "fr-wire-2-5",
    name: "FR PVC House Wire 2.5 sq mm",
    category: "Electrical",
    supplierId: "voltcore",
    price: 2280,
    unit: "90 m coil",
    moq: 4,
    stock: 780,
    grade: "IS 694",
    description:
      "Flame-retardant single-core copper wire for lighting and 6 A socket circuits in concealed conduit.",
    specs: [
      { label: "Conductor", value: "99.97% bare copper" },
      { label: "Insulation", value: "FR PVC, 70°C" },
      { label: "Voltage", value: "1100 V grade" },
      { label: "Coil", value: "90 m" },
    ],
  },
  {
    id: "fr-wire-4",
    name: "FR PVC House Wire 4 sq mm",
    category: "Electrical",
    supplierId: "voltcore",
    price: 3560,
    unit: "90 m coil",
    moq: 2,
    stock: 520,
    grade: "IS 694",
    description:
      "Heavier-gauge copper wire for 16 A power circuits, AC points and geyser lines.",
    specs: [
      { label: "Current rating", value: "24 A" },
      { label: "Conductor", value: "Annealed copper" },
      { label: "Insulation", value: "FR PVC" },
      { label: "Coil", value: "90 m" },
    ],
  },
  {
    id: "pvc-conduit",
    name: "PVC Concealed Conduit 25 mm",
    category: "Electrical",
    supplierId: "voltcore",
    price: 165,
    unit: "3 m length",
    moq: 50,
    stock: 3600,
    grade: "IS 9537 Part 3",
    description:
      "Medium-duty ISI conduit for wall chasing and slab-embedded wiring runs.",
    specs: [
      { label: "Diameter", value: "25 mm" },
      { label: "Duty", value: "Medium (2 mm wall)" },
      { label: "Length", value: "3 m" },
      { label: "Fittings", value: "Bends & couplers available" },
    ],
  },
  {
    id: "distribution-board",
    name: "8-Way Distribution Board with MCBs",
    category: "Electrical",
    supplierId: "voltcore",
    price: 6850,
    unit: "unit",
    moq: 1,
    stock: 190,
    grade: "IS 8623",
    description:
      "Double-door SPN board pre-fitted with RCCB and MCBs for a typical 2–3 BHK residence.",
    specs: [
      { label: "Ways", value: "8 (SPN)" },
      { label: "Protection", value: "40 A RCCB + 8 MCBs" },
      { label: "Enclosure", value: "Powder-coated CRCA" },
      { label: "Rating", value: "10 kA breaking capacity" },
    ],
  },
  {
    id: "modular-switch-set",
    name: "Modular Switch & Socket Set (Room Kit)",
    category: "Electrical",
    supplierId: "voltcore",
    price: 2950,
    unit: "room kit",
    moq: 4,
    stock: 340,
    grade: "IS 3854",
    description:
      "Per-room kit of switches, 6/16 A sockets, plates and metal boxes in a matte finish range.",
    specs: [
      { label: "Includes", value: "6 switches, 2 sockets, plates, boxes" },
      { label: "Finish", value: "Matte white / graphite" },
      { label: "Rating", value: "6 A & 16 A" },
      { label: "Warranty", value: "3 years" },
    ],
  },
  {
    id: "led-panel",
    name: "LED Recessed Panel Light 15 W (Pack of 10)",
    category: "Electrical",
    supplierId: "voltcore",
    price: 4400,
    unit: "pack of 10",
    moq: 2,
    stock: 260,
    grade: "BIS registered",
    description:
      "Slim recessed panels for false ceilings with flicker-free driver and neutral-white output.",
    specs: [
      { label: "Wattage", value: "15 W each" },
      { label: "Output", value: "1350 lm, 4000 K" },
      { label: "Cut-out", value: "150 mm round" },
      { label: "Life", value: "25,000 hours" },
    ],
  },
  {
    id: "vitrified-tile",
    name: "Double-Charge Vitrified Tile 600×600 mm",
    category: "Flooring & Tiles",
    supplierId: "tilehaus",
    price: 62,
    unit: "sq ft",
    moq: 400,
    stock: 42000,
    grade: "IS 15622 Group BIa",
    description:
      "Low-porosity double-charge floor tile for living areas and bedrooms with deep-body wear resistance.",
    specs: [
      { label: "Size", value: "600 × 600 mm" },
      { label: "Water absorption", value: "< 0.5%" },
      { label: "Thickness", value: "9 mm" },
      { label: "Coverage", value: "4 tiles = 15.5 sq ft" },
    ],
  },
  {
    id: "wall-tile",
    name: "Glazed Wall Tile 300×600 mm",
    category: "Flooring & Tiles",
    supplierId: "tilehaus",
    price: 44,
    unit: "sq ft",
    moq: 250,
    stock: 26000,
    grade: "IS 15622",
    description:
      "Bathroom and kitchen wall tile with a satin glaze and rectified edges for thin grout lines.",
    specs: [
      { label: "Size", value: "300 × 600 mm" },
      { label: "Finish", value: "Satin glaze" },
      { label: "Thickness", value: "8 mm" },
      { label: "Edge", value: "Rectified" },
    ],
  },
  {
    id: "granite-slab",
    name: "Polished Granite Slab 18 mm",
    category: "Flooring & Tiles",
    supplierId: "tilehaus",
    price: 185,
    unit: "sq ft",
    moq: 100,
    stock: 8400,
    grade: "Natural stone",
    description:
      "Mirror-polished granite for kitchen counters, staircase treads and window sills, cut to size.",
    specs: [
      { label: "Thickness", value: "18 mm" },
      { label: "Finish", value: "Mirror polish" },
      { label: "Edge profile", value: "Bullnose on request" },
      { label: "Cutting", value: "Free straight cuts" },
    ],
  },
  {
    id: "tile-adhesive",
    name: "Polymer Tile Adhesive 20 kg",
    category: "Flooring & Tiles",
    supplierId: "tilehaus",
    price: 520,
    unit: "20 kg bag",
    moq: 20,
    stock: 2600,
    grade: "IS 15477 Type 3",
    description:
      "Cement-based adhesive for vitrified tile fixing over screed and existing floors.",
    specs: [
      { label: "Coverage", value: "35–40 sq ft per bag" },
      { label: "Open time", value: "20 minutes" },
      { label: "Pot life", value: "2 hours" },
      { label: "Type", value: "Type 3 (high polymer)" },
    ],
  },
  {
    id: "epoxy-grout",
    name: "Epoxy Tile Grout 1 kg",
    category: "Flooring & Tiles",
    supplierId: "tilehaus",
    price: 690,
    unit: "1 kg kit",
    moq: 10,
    stock: 900,
    grade: "EN 13888 RG",
    description:
      "Stain-proof, waterproof epoxy grout for bathroom and kitchen joints — no sealing required.",
    specs: [
      { label: "Joint width", value: "2–12 mm" },
      { label: "Coverage", value: "~55 sq ft at 3 mm" },
      { label: "Cure", value: "24 h light traffic" },
      { label: "Shades", value: "18 colours" },
    ],
  },
  {
    id: "laminate-floor",
    name: "Laminate Wooden Flooring 8 mm",
    category: "Flooring & Tiles",
    supplierId: "tilehaus",
    price: 118,
    unit: "sq ft",
    moq: 200,
    stock: 14000,
    grade: "AC4",
    description:
      "Click-lock laminate planks with an AC4 wear layer for bedrooms and study rooms.",
    specs: [
      { label: "Thickness", value: "8 mm + underlay" },
      { label: "Wear class", value: "AC4 residential heavy" },
      { label: "Plank", value: "1215 × 195 mm" },
      { label: "Install", value: "Floating click-lock" },
    ],
  },
  {
    id: "wall-putty",
    name: "White Cement Wall Putty 40 kg",
    category: "Paint & Finishes",
    supplierId: "chromacoat",
    price: 1180,
    unit: "40 kg bag",
    moq: 10,
    stock: 1900,
    grade: "Two-coat grade",
    description:
      "White cement putty that levels plaster and gives paint an even, low-absorption base.",
    specs: [
      { label: "Coverage", value: "160–180 sq ft, two coats" },
      { label: "Drying", value: "4–6 hours between coats" },
      { label: "Base", value: "White cement + polymer" },
      { label: "Recoat", value: "Sand before primer" },
    ],
  },
  {
    id: "wall-primer",
    name: "Water-Based Wall Primer 20 L",
    category: "Paint & Finishes",
    supplierId: "chromacoat",
    price: 3450,
    unit: "20 L bucket",
    moq: 2,
    stock: 480,
    grade: "Interior/exterior",
    description:
      "Alkali-resistant primer that seals putty and improves topcoat spread and adhesion.",
    specs: [
      { label: "Coverage", value: "1600–1900 sq ft" },
      { label: "Dry to recoat", value: "4 hours" },
      { label: "Thinning", value: "Up to 50% water" },
      { label: "Finish", value: "Matt white" },
    ],
  },
  {
    id: "interior-emulsion",
    name: "Premium Interior Emulsion 20 L",
    category: "Paint & Finishes",
    supplierId: "chromacoat",
    price: 7900,
    unit: "20 L bucket",
    moq: 2,
    stock: 420,
    grade: "Low VOC",
    description:
      "Washable acrylic emulsion with a smooth sheen for living rooms, bedrooms and passages.",
    specs: [
      { label: "Coverage", value: "1400–1600 sq ft, two coats" },
      { label: "Finish", value: "Soft sheen" },
      { label: "VOC", value: "< 50 g/l" },
      { label: "Tinting", value: "Machine tinted to shade card" },
    ],
  },
  {
    id: "exterior-emulsion",
    name: "Weatherproof Exterior Emulsion 20 L",
    category: "Paint & Finishes",
    supplierId: "chromacoat",
    price: 9400,
    unit: "20 L bucket",
    moq: 2,
    stock: 360,
    grade: "7-year warranty",
    description:
      "UV and rain-resistant exterior paint with algae protection for facades and boundary walls.",
    specs: [
      { label: "Coverage", value: "1200–1400 sq ft, two coats" },
      { label: "Warranty", value: "7 years film integrity" },
      { label: "Resistance", value: "Algae & fungus" },
      { label: "Finish", value: "Matt" },
    ],
  },
  {
    id: "enamel-paint",
    name: "Synthetic Enamel Paint 4 L",
    category: "Paint & Finishes",
    supplierId: "chromacoat",
    price: 1650,
    unit: "4 L tin",
    moq: 4,
    stock: 540,
    grade: "High gloss",
    description:
      "Oil-based enamel for grills, railings, doors and window frames with a hard gloss film.",
    specs: [
      { label: "Coverage", value: "440–500 sq ft, two coats" },
      { label: "Finish", value: "High gloss" },
      { label: "Thinner", value: "Mineral turpentine" },
      { label: "Dry", value: "Hard dry 16 hours" },
    ],
  },
  {
    id: "waterproof-coating",
    name: "Acrylic Waterproof Coating 20 kg",
    category: "Paint & Finishes",
    supplierId: "chromacoat",
    price: 5600,
    unit: "20 kg bucket",
    moq: 2,
    stock: 300,
    grade: "Elastomeric",
    description:
      "Crack-bridging elastomeric membrane for terraces, chajjas, sunken slabs and wet areas.",
    specs: [
      { label: "Elongation", value: "300%" },
      { label: "Coverage", value: "300–350 sq ft, two coats" },
      { label: "Reinforcement", value: "Use with fibre mesh" },
      { label: "Cure", value: "7 days full" },
    ],
  },
  {
    id: "bitumen-membrane",
    name: "APP Bitumen Damp-Proof Membrane 3 mm",
    category: "Paint & Finishes",
    supplierId: "chromacoat",
    price: 4200,
    unit: "10 m roll",
    moq: 4,
    stock: 260,
    grade: "APP modified",
    description:
      "Torch-applied membrane for plinth-level damp proofing, footings and basement walls.",
    specs: [
      { label: "Thickness", value: "3 mm" },
      { label: "Roll", value: "10 m × 1 m" },
      { label: "Application", value: "Torch bonded" },
      { label: "Reinforcement", value: "Polyester mat" },
    ],
  },
  {
    id: "flush-door",
    name: "Solid-Core Flush Door 32 mm",
    category: "Interiors & Fittings",
    supplierId: "interia",
    price: 6800,
    unit: "door shutter",
    moq: 4,
    stock: 220,
    grade: "IS 2202 BWP",
    description:
      "Hardwood block-board core flush shutter, factory pressed and ready for laminate or paint.",
    specs: [
      { label: "Thickness", value: "32 mm" },
      { label: "Size", value: "Made to opening, up to 900 × 2100 mm" },
      { label: "Core", value: "Solid hardwood block" },
      { label: "Bond", value: "BWP phenolic" },
    ],
  },
  {
    id: "upvc-window",
    name: "UPVC Sliding Window (2 Track)",
    category: "Interiors & Fittings",
    supplierId: "interia",
    price: 690,
    unit: "sq ft",
    moq: 60,
    stock: 5200,
    grade: "Lead-free UPVC",
    description:
      "Multi-chambered UPVC sliding window with 5 mm glass, EPDM gaskets and mesh track option.",
    specs: [
      { label: "Glazing", value: "5 mm clear / 6 mm toughened" },
      { label: "Profile", value: "60 mm two-track" },
      { label: "Hardware", value: "Touch lock, SS rollers" },
      { label: "Lead time", value: "7 days made-to-size" },
    ],
  },
  {
    id: "gypsum-board",
    name: "Gypsum False Ceiling Board 12.5 mm",
    category: "Interiors & Fittings",
    supplierId: "interia",
    price: 780,
    unit: "8×4 sheet",
    moq: 20,
    stock: 1400,
    grade: "IS 2095",
    description:
      "Tapered-edge plasterboard for suspended ceilings with concealed GI grid systems.",
    specs: [
      { label: "Size", value: "2440 × 1220 mm" },
      { label: "Thickness", value: "12.5 mm" },
      { label: "Edge", value: "Tapered" },
      { label: "Grid", value: "GI channels sold separately" },
    ],
  },
  {
    id: "gi-ceiling-channel",
    name: "GI Ceiling Grid Channel Set",
    category: "Interiors & Fittings",
    supplierId: "interia",
    price: 2400,
    unit: "100 sq ft set",
    moq: 4,
    stock: 480,
    grade: "0.55 mm GI",
    description:
      "Perimeter, intermediate and ceiling sections with soffit cleats for false-ceiling framing.",
    specs: [
      { label: "Coverage", value: "100 sq ft per set" },
      { label: "Thickness", value: "0.55 mm galvanised" },
      { label: "Includes", value: "Channels, cleats, rods, screws" },
      { label: "Spacing", value: "450 mm centres" },
    ],
  },
  {
    id: "prelam-mdf",
    name: "Pre-Laminated MDF Board 18 mm",
    category: "Interiors & Fittings",
    supplierId: "interia",
    price: 2450,
    unit: "8×4 sheet",
    moq: 8,
    stock: 640,
    grade: "IS 14587",
    description:
      "Double-sided pre-laminated board for wardrobes, kitchen carcasses and study units.",
    specs: [
      { label: "Size", value: "2440 × 1220 mm" },
      { label: "Thickness", value: "18 mm" },
      { label: "Finish", value: "Both sides laminated" },
      { label: "Density", value: "760 kg/m³" },
    ],
  },
  {
    id: "door-hardware",
    name: "SS Door Hardware Set",
    category: "Interiors & Fittings",
    supplierId: "interia",
    price: 1850,
    unit: "set",
    moq: 5,
    stock: 380,
    grade: "SS 304",
    description:
      "Stainless mortise lock, handles, hinges and door stopper — one set per internal door.",
    specs: [
      { label: "Lock", value: "Mortise, 3 keys" },
      { label: "Hinges", value: "4 in × 3, SS 304" },
      { label: "Finish", value: "Satin steel" },
      { label: "Includes", value: "Handles, stopper, screws" },
    ],
  },
  {
    id: "modular-kitchen-base",
    name: "Modular Kitchen Base Unit (Plywood Carcass)",
    category: "Interiors & Fittings",
    supplierId: "nestcraft",
    price: 1450,
    unit: "sq ft",
    moq: 40,
    stock: 3200,
    grade: "BWP 710 ply",
    description:
      "Made-to-size base cabinets with BWP plywood carcass, laminate shutters and soft-close hinges.",
    specs: [
      { label: "Carcass", value: "18 mm BWP plywood" },
      { label: "Shutter", value: "1 mm laminate finish" },
      { label: "Hardware", value: "Soft-close hinges" },
      { label: "Lead time", value: "10-14 days" },
    ],
  },
  {
    id: "kitchen-tandem-drawer",
    name: "Tandem Box Drawer Set",
    category: "Interiors & Fittings",
    supplierId: "nestcraft",
    price: 3200,
    unit: "set",
    moq: 4,
    stock: 460,
    grade: "Soft-close 40 kg",
    description:
      "Steel tandem drawer boxes with full-extension soft-close runners for kitchen and wardrobe units.",
    specs: [
      { label: "Load rating", value: "40 kg per drawer" },
      { label: "Extension", value: "Full, soft close" },
      { label: "Depth", value: "500 mm" },
      { label: "Finish", value: "Powder-coated grey" },
    ],
  },
  {
    id: "quartz-countertop",
    name: "Engineered Quartz Countertop 20 mm",
    category: "Interiors & Fittings",
    supplierId: "tilehaus",
    price: 480,
    unit: "sq ft",
    moq: 30,
    stock: 2400,
    grade: "93% quartz",
    description:
      "Stain-resistant engineered quartz slab for kitchen counters, with edge polishing and sink cut-out.",
    specs: [
      { label: "Thickness", value: "20 mm" },
      { label: "Water absorption", value: "<0.05%" },
      { label: "Edge", value: "Mitred / bullnose" },
      { label: "Includes", value: "Sink cut-out" },
    ],
  },
  {
    id: "wardrobe-sliding",
    name: "Sliding Wardrobe Shutter System",
    category: "Interiors & Fittings",
    supplierId: "nestcraft",
    price: 980,
    unit: "sq ft",
    moq: 50,
    stock: 1800,
    grade: "Aluminium frame",
    description:
      "Two-shutter sliding wardrobe with aluminium profile, mirror or laminate infill and floor track.",
    specs: [
      { label: "Profile", value: "Anodised aluminium" },
      { label: "Infill", value: "Laminate / mirror" },
      { label: "Rollers", value: "Nylon, dust-sealed" },
      { label: "Max height", value: "2400 mm" },
    ],
  },
  {
    id: "wardrobe-internals",
    name: "Wardrobe Internal Accessory Kit",
    category: "Interiors & Fittings",
    supplierId: "nestcraft",
    price: 5400,
    unit: "kit",
    moq: 2,
    stock: 240,
    grade: "SS 202",
    description:
      "Pull-out trouser rack, tie holder, hanging rod and shelf brackets for one wardrobe bay.",
    specs: [
      { label: "Includes", value: "Rack, rod, brackets" },
      { label: "Finish", value: "Satin chrome" },
      { label: "Bay width", value: "900 mm" },
      { label: "Fixing", value: "Screw-on" },
    ],
  },
  {
    id: "wpc-wall-panel",
    name: "WPC Louvre Wall Panel",
    category: "Interiors & Fittings",
    supplierId: "interia",
    price: 260,
    unit: "sq ft",
    moq: 60,
    stock: 4100,
    grade: "Termite-proof WPC",
    description:
      "Fluted wood-plastic composite panelling for TV walls, headboards and entrance foyers.",
    specs: [
      { label: "Size", value: "2900 x 160 mm" },
      { label: "Thickness", value: "12 mm" },
      { label: "Finish", value: "Matte woodgrain" },
      { label: "Fixing", value: "Adhesive + pins" },
    ],
  },
  {
    id: "pop-cornice",
    name: "POP Cornice & Moulding",
    category: "Interiors & Fittings",
    supplierId: "interia",
    price: 95,
    unit: "running ft",
    moq: 100,
    stock: 6800,
    grade: "Gypsum POP",
    description:
      "Pre-cast plaster cornices and coving for ceiling perimeters and drop-ceiling detailing.",
    specs: [
      { label: "Profile depth", value: "75 mm" },
      { label: "Length", value: "3 m sections" },
      { label: "Finish", value: "Paint ready" },
      { label: "Fixing", value: "Gypsum bond" },
    ],
  },
  {
    id: "cove-lighting-profile",
    name: "Aluminium Cove Lighting Profile",
    category: "Interiors & Fittings",
    supplierId: "lumina-decor",
    price: 340,
    unit: "2 m length",
    moq: 20,
    stock: 1500,
    grade: "6063 aluminium",
    description:
      "Recessed profile with diffuser for LED strip lighting in false ceilings and niches.",
    specs: [
      { label: "Length", value: "2 m" },
      { label: "Diffuser", value: "Frosted PC" },
      { label: "Mounting", value: "Recessed / surface" },
      { label: "Strip width", value: "Up to 12 mm" },
    ],
  },
  {
    id: "decor-pendant-light",
    name: "Designer Pendant Light",
    category: "Interiors & Fittings",
    supplierId: "lumina-decor",
    price: 2650,
    unit: "piece",
    moq: 3,
    stock: 320,
    grade: "E27, 3000K",
    description:
      "Hand-finished metal and glass pendant for dining and island counters, with 1.5 m adjustable cord.",
    specs: [
      { label: "Holder", value: "E27" },
      { label: "Shade", value: "Glass + brushed brass" },
      { label: "Drop", value: "Adjustable to 1.5 m" },
      { label: "Dimmable", value: "Yes, with LED driver" },
    ],
  },
  {
    id: "wall-mirror-led",
    name: "Backlit LED Wall Mirror",
    category: "Interiors & Fittings",
    supplierId: "lumina-decor",
    price: 7900,
    unit: "piece",
    moq: 2,
    stock: 180,
    grade: "5 mm silvered",
    description:
      "Anti-fog bathroom and dresser mirror with perimeter LED backlight and touch switch.",
    specs: [
      { label: "Size", value: "900 x 600 mm" },
      { label: "Light", value: "4000K perimeter LED" },
      { label: "Feature", value: "Anti-fog demister" },
      { label: "Rating", value: "IP44" },
    ],
  },
  {
    id: "roller-blinds",
    name: "Blackout Roller Blind",
    category: "Interiors & Fittings",
    supplierId: "lumina-decor",
    price: 210,
    unit: "sq ft",
    moq: 40,
    stock: 3600,
    grade: "100% blackout",
    description:
      "Made-to-size roller blinds with aluminium cassette, chain control and blackout fabric.",
    specs: [
      { label: "Fabric", value: "Coated polyester" },
      { label: "Control", value: "Side chain" },
      { label: "Cassette", value: "Aluminium" },
      { label: "Lead time", value: "5 days" },
    ],
  },
  {
    id: "modular-wardrobe-handles",
    name: "Aluminium Gola Profile Handle",
    category: "Interiors & Fittings",
    supplierId: "nestcraft",
    price: 420,
    unit: "running ft",
    moq: 30,
    stock: 2100,
    grade: "Anodised",
    description:
      "Handle-less G and L profile for modular kitchens and wardrobes, with end caps and joiners.",
    specs: [
      { label: "Profile", value: "G / L / C" },
      { label: "Finish", value: "Champagne anodised" },
      { label: "Length", value: "Cut to size" },
      { label: "Includes", value: "End caps" },
    ],
  },
  {
    id: "engineered-wood-floor",
    name: "Engineered Wood Flooring Plank",
    category: "Interiors & Fittings",
    supplierId: "interia",
    price: 385,
    unit: "sq ft",
    moq: 120,
    stock: 5200,
    grade: "AC4 wear layer",
    description:
      "Click-lock engineered oak planks with underlay for bedrooms and living rooms.",
    specs: [
      { label: "Thickness", value: "12 mm" },
      { label: "Wear layer", value: "AC4" },
      { label: "Locking", value: "Click, glueless" },
      { label: "Includes", value: "2 mm underlay" },
    ],
  },
  {
    id: "wardrobe-loft-shutter",
    name: "Acrylic Finish Loft Shutter",
    category: "Interiors & Fittings",
    supplierId: "nestcraft",
    price: 1180,
    unit: "sq ft",
    moq: 25,
    stock: 900,
    grade: "High-gloss acrylic",
    description:
      "High-gloss acrylic-faced MDF shutters for lofts and overhead storage, edge-banded on all sides.",
    specs: [
      { label: "Core", value: "18 mm MDF" },
      { label: "Face", value: "1 mm acrylic gloss" },
      { label: "Edge", value: "PVC banding" },
      { label: "Warranty", value: "5 years" },
    ],
  },
];

export const getProduct = (id: string) => PRODUCTS.find((p) => p.id === id);
export const getSupplier = (id: string) => SUPPLIERS.find((s) => s.id === id);
export const supplierProducts = (id: string) =>
  PRODUCTS.filter((p) => p.supplierId === id);

export const formatINR = (value: number) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: value % 1 === 0 ? 0 : 2,
  }).format(value);
