/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildRouteImport } from './routes/build'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as BuildIndexRouteImport } from './routes/build.index'
import { Route as BuildPhaseIdRouteImport } from './routes/build.$phaseId'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as SuppliersSupplierIdRouteImport } from './routes/suppliers.$supplierId'
import { Route as VisualiserIndexRouteImport } from './routes/visualiser.index'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdDrawingsRouteImport } from './routes/projects.$projectId.drawings'
import { Route as ProjectsProjectIdModelRouteImport } from './routes/projects.$projectId.model'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildIndexRoute = BuildIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuildRoute,
} as any)
const BuildPhaseIdRoute = BuildPhaseIdRouteImport.update({
  id: '/$phaseId',
  path: '/$phaseId',
  getParentRoute: () => BuildRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersSupplierIdRoute = SuppliersSupplierIdRouteImport.update({
  id: '/suppliers/$supplierId',
  path: '/suppliers/$supplierId',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualiserIndexRoute = VisualiserIndexRouteImport.update({
  id: '/visualiser/',
  path: '/visualiser/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdDrawingsRoute =
  ProjectsProjectIdDrawingsRouteImport.update({
    id: '/drawings',
    path: '/drawings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdModelRoute = ProjectsProjectIdModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build': typeof BuildRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/products': typeof ProductsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/build/$phaseId': typeof BuildPhaseIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/build/': typeof BuildIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/visualiser/': typeof VisualiserIndexRoute
  '/projects/$projectId/drawings': typeof ProjectsProjectIdDrawingsRoute
  '/projects/$projectId/model': typeof ProjectsProjectIdModelRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/build/$phaseId': typeof BuildPhaseIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/build': typeof BuildIndexRoute
  '/products': typeof ProductsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/visualiser': typeof VisualiserIndexRoute
  '/projects/$projectId/drawings': typeof ProjectsProjectIdDrawingsRoute
  '/projects/$projectId/model': typeof ProjectsProjectIdModelRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build': typeof BuildRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/products': typeof ProductsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/build/$phaseId': typeof BuildPhaseIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/build/': typeof BuildIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/visualiser/': typeof VisualiserIndexRoute
  '/projects/$projectId/drawings': typeof ProjectsProjectIdDrawingsRoute
  '/projects/$projectId/model': typeof ProjectsProjectIdModelRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/build'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/projects'
    | '/build/$phaseId'
    | '/products/$productId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/suppliers/$supplierId'
    | '/build/'
    | '/products/'
    | '/projects/'
    | '/suppliers/'
    | '/visualiser/'
    | '/projects/$projectId/drawings'
    | '/projects/$projectId/model'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/build/$phaseId'
    | '/products/$productId'
    | '/projects/new'
    | '/suppliers/$supplierId'
    | '/build'
    | '/products'
    | '/projects'
    | '/suppliers'
    | '/visualiser'
    | '/projects/$projectId/drawings'
    | '/projects/$projectId/model'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/build'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/projects'
    | '/build/$phaseId'
    | '/products/$productId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/suppliers/$supplierId'
    | '/build/'
    | '/products/'
    | '/projects/'
    | '/suppliers/'
    | '/visualiser/'
    | '/projects/$projectId/drawings'
    | '/projects/$projectId/model'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildRoute: typeof BuildRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SuppliersSupplierIdRoute: typeof SuppliersSupplierIdRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
  VisualiserIndexRoute: typeof VisualiserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/': {
      id: '/build/'
      path: '/'
      fullPath: '/build/'
      preLoaderRoute: typeof BuildIndexRouteImport
      parentRoute: typeof BuildRoute
    }
    '/build/$phaseId': {
      id: '/build/$phaseId'
      path: '/$phaseId'
      fullPath: '/build/$phaseId'
      preLoaderRoute: typeof BuildPhaseIdRouteImport
      parentRoute: typeof BuildRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$supplierId': {
      id: '/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof SuppliersSupplierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualiser/': {
      id: '/visualiser/'
      path: '/visualiser'
      fullPath: '/visualiser/'
      preLoaderRoute: typeof VisualiserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/drawings': {
      id: '/projects/$projectId/drawings'
      path: '/drawings'
      fullPath: '/projects/$projectId/drawings'
      preLoaderRoute: typeof ProjectsProjectIdDrawingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/model': {
      id: '/projects/$projectId/model'
      path: '/model'
      fullPath: '/projects/$projectId/model'
      preLoaderRoute: typeof ProjectsProjectIdModelRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface BuildRouteChildren {
  BuildPhaseIdRoute: typeof BuildPhaseIdRoute
  BuildIndexRoute: typeof BuildIndexRoute
}

const BuildRouteChildren: BuildRouteChildren = {
  BuildPhaseIdRoute: BuildPhaseIdRoute,
  BuildIndexRoute: BuildIndexRoute,
}

const BuildRouteWithChildren = BuildRoute._addFileChildren(BuildRouteChildren)

interface ProductsRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdDrawingsRoute: typeof ProjectsProjectIdDrawingsRoute
  ProjectsProjectIdModelRoute: typeof ProjectsProjectIdModelRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdDrawingsRoute: ProjectsProjectIdDrawingsRoute,
  ProjectsProjectIdModelRoute: ProjectsProjectIdModelRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildRoute: BuildRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  SuppliersSupplierIdRoute: SuppliersSupplierIdRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
  VisualiserIndexRoute: VisualiserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
