/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildRouteImport } from './routes/build'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as BuildIndexRouteImport } from './routes/build.index'
import { Route as BuildPhaseIdRouteImport } from './routes/build.$phaseId'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as SuppliersSupplierIdRouteImport } from './routes/suppliers.$supplierId'
import { Route as VisualiserIndexRouteImport } from './routes/visualiser.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildIndexRoute = BuildIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuildRoute,
} as any)
const BuildPhaseIdRoute = BuildPhaseIdRouteImport.update({
  id: '/$phaseId',
  path: '/$phaseId',
  getParentRoute: () => BuildRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRoute,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersSupplierIdRoute = SuppliersSupplierIdRouteImport.update({
  id: '/suppliers/$supplierId',
  path: '/suppliers/$supplierId',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualiserIndexRoute = VisualiserIndexRouteImport.update({
  id: '/visualiser/',
  path: '/visualiser/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build': typeof BuildRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/products': typeof ProductsRouteWithChildren
  '/build/$phaseId': typeof BuildPhaseIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/build/': typeof BuildIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/visualiser/': typeof VisualiserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/build/$phaseId': typeof BuildPhaseIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/build': typeof BuildIndexRoute
  '/products': typeof ProductsIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/visualiser': typeof VisualiserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build': typeof BuildRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/products': typeof ProductsRouteWithChildren
  '/build/$phaseId': typeof BuildPhaseIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/build/': typeof BuildIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/visualiser/': typeof VisualiserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/build'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/build/$phaseId'
    | '/products/$productId'
    | '/suppliers/$supplierId'
    | '/build/'
    | '/products/'
    | '/suppliers/'
    | '/visualiser/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/build/$phaseId'
    | '/products/$productId'
    | '/suppliers/$supplierId'
    | '/build'
    | '/products'
    | '/suppliers'
    | '/visualiser'
  id:
    | '__root__'
    | '/'
    | '/build'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/build/$phaseId'
    | '/products/$productId'
    | '/suppliers/$supplierId'
    | '/build/'
    | '/products/'
    | '/suppliers/'
    | '/visualiser/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildRoute: typeof BuildRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  SuppliersSupplierIdRoute: typeof SuppliersSupplierIdRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
  VisualiserIndexRoute: typeof VisualiserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/': {
      id: '/build/'
      path: '/'
      fullPath: '/build/'
      preLoaderRoute: typeof BuildIndexRouteImport
      parentRoute: typeof BuildRoute
    }
    '/build/$phaseId': {
      id: '/build/$phaseId'
      path: '/$phaseId'
      fullPath: '/build/$phaseId'
      preLoaderRoute: typeof BuildPhaseIdRouteImport
      parentRoute: typeof BuildRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$supplierId': {
      id: '/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof SuppliersSupplierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualiser/': {
      id: '/visualiser/'
      path: '/visualiser'
      fullPath: '/visualiser/'
      preLoaderRoute: typeof VisualiserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BuildRouteChildren {
  BuildPhaseIdRoute: typeof BuildPhaseIdRoute
  BuildIndexRoute: typeof BuildIndexRoute
}

const BuildRouteChildren: BuildRouteChildren = {
  BuildPhaseIdRoute: BuildPhaseIdRoute,
  BuildIndexRoute: BuildIndexRoute,
}

const BuildRouteWithChildren = BuildRoute._addFileChildren(BuildRouteChildren)

interface ProductsRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildRoute: BuildRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ProductsRoute: ProductsRouteWithChildren,
  SuppliersSupplierIdRoute: SuppliersSupplierIdRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
  VisualiserIndexRoute: VisualiserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
